sudo: false
language: python
python:
  - "3.5"

env:
  - TOXENV=py35
  - TOXENV=packaging
  - TOXENV=style

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov
